# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CLOUDFORMATION
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - CSS
  - EDITORCONFIG
  # - SPELL # Uncomment to disable checks of spelling mistakes
  - JAVASCRIPT
  - TEKTON
DISABLE_LINTERS:
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_KICS
  - SPELL_PROSELINT
  - SPELL_MISSPELL
  - SPELL_VALE
  - SPELL_LYCHEE
DISABLE_ERRORS_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
PRINT_ALL_FILES: false
